import Matter from 'matter-js';
import type {Member,Mode,Settings,Result} from '../types';
import {placementAward,clearBonus,type Grade} from './scoring';
import {difficulty} from './difficulty';
import {createPiece} from './piece';
import {Sound} from './audio';
import {outside,shuffled,targetFor} from './rules';
import {createSeesaw,applyBearing,limitSeesaw,PIVOT} from './seesaw';
const {Engine,Composite}=Matter;
export type Snapshot={count:number;target:number;seconds:number;current:Member|undefined;next:Member|undefined;phase:string;tilt:number;angle:number;hint:string;stability:number;score:number;perfects:number;feedback:{grade:Grade;points:number}|null};
export class Game{
 engine=Engine.create({positionIterations:10,velocityIterations:10,constraintIterations:4});seesaw:ReturnType<typeof createSeesaw>;platform:Matter.Body;
 paused=false;bearingLoad=0;
 score=0;perfects=0;failureReason='';stableTilt=0;stablePeak=0;tiltTotal=0;tiltSamples=0;maxTilt=0;feedback:{grade:Grade;points:number}|null=null;feedbackUntil=0;
 angle=0;hint='';
 resizeObserver:ResizeObserver;
 contacts=new Map<string,{a:Matter.Body;b:Matter.Body;time:number}>();
 pieces:{body:Matter.Body;member:Member;dx:number;dy:number}[]=[];queue:Member[];count=0;seconds=0;phase='ready';settled=0;released=0;raf=0;last=0;acc=0;ui=0;camera=0;drag=false;pointer=-1;pos={x:195,y:90};sound:Sound;images=new Map<string,HTMLImageElement>();debug:boolean;disposed=false;fps=60;
 constructor(public canvas:HTMLCanvasElement,public mode:Mode,all:Member[],public settings:Settings,public update:(s:Snapshot)=>void,public finish:(r:Result)=>void,order?:string[]){this.seesaw=createSeesaw(mode);this.platform=this.seesaw.board;const replay=order?.map(id=>all.find(m=>m.id===id)).filter((m):m is Member=>!!m);this.queue=replay&&replay.length===targetFor(mode,all.length)&&new Set(order).size===replay.length?replay:shuffled(all).slice(0,targetFor(mode,all.length));this.sound=new Sound(settings);this.debug=new URLSearchParams(location.search).get('debug')==='true';this.engine.gravity.y=.75;Composite.add(this.engine.world,[this.platform,this.seesaw.pivot]);for(const m of all){const im=new Image();im.onerror=()=>{im.onerror=null;im.src='/fallback.svg';};im.src=m.image;this.images.set(m.id,im);}canvas.addEventListener('pointerdown',this.down);canvas.addEventListener('pointermove',this.move);canvas.addEventListener('pointerup',this.up);canvas.addEventListener('pointercancel',this.cancel);canvas.addEventListener('keydown',this.key);this.resizeObserver=new ResizeObserver(this.resize);if(canvas.parentElement)this.resizeObserver.observe(canvas.parentElement);this.resize();this.sound.unlock();this.emit();this.raf=requestAnimationFrame(this.loop);}
 resize=()=>{const parent=this.canvas.parentElement;if(!parent)return;const css=getComputedStyle(parent);const width=parent.clientWidth-parseFloat(css.paddingLeft)-parseFloat(css.paddingRight);const height=parent.clientHeight-parseFloat(css.paddingTop)-parseFloat(css.paddingBottom);const scale=Math.max(.1,Math.min(width/390,height/650));this.canvas.style.width=`${390*scale}px`;this.canvas.style.height=`${650*scale}px`;};
 emit(){this.update({count:this.count,target:this.queue.length,seconds:this.seconds,current:this.queue[this.count],next:this.queue[this.count+1],phase:this.phase,tilt:this.platform.angle*180/Math.PI,angle:this.angle*180/Math.PI,hint:this.hint,stability:Math.min(1,this.settled/this.stableTime),score:this.score,perfects:this.perfects,feedback:this.seconds<this.feedbackUntil?this.feedback:null});}
 point=(e:PointerEvent)=>{const r=this.canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*390,y:(e.clientY-r.top)/r.height*650-this.camera};};
 down=(e:PointerEvent)=>{if(this.paused||this.phase!=='ready'||this.drag)return;const p=this.point(e);if(Math.abs(p.x-this.pos.x)>50||Math.abs(p.y-this.pos.y)>50)return;e.preventDefault();this.hint='';this.drag=true;this.pointer=e.pointerId;this.canvas.setPointerCapture(e.pointerId);this.sound.unlock();this.sound.play('pick');};
 move=(e:PointerEvent)=>{if(!this.drag||e.pointerId!==this.pointer)return;e.preventDefault();const p=this.point(e);this.pos={x:Math.max(20,Math.min(370,p.x)),y:Math.min(530,Math.max(25-this.camera,p.y))};};
 up=(e:PointerEvent)=>{if(this.drag&&e.pointerId===this.pointer){this.drag=false;this.drop();}};
 cancel=()=>{this.drag=false;this.pos={x:195,y:90-this.camera};};
 get stableTime(){return difficulty[this.mode].stableTime;}
 rotate=(direction:number)=>{if(this.paused||this.phase!=='ready')return;this.angle=Math.round((this.angle+direction*Math.PI/12)/(Math.PI/12))*Math.PI/12;this.angle=Math.atan2(Math.sin(this.angle),Math.cos(this.angle));this.hint='';this.emit();};
 key=(e:KeyboardEvent)=>{if(this.paused||this.phase!=='ready')return;const k=e.key.toLowerCase();if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp',' ','Enter'].includes(e.key)||['q','e'].includes(k))e.preventDefault();if(k==='q')this.rotate(-1);if(k==='e')this.rotate(1);if(e.key==='ArrowLeft')this.pos.x=Math.max(25,this.pos.x-8);if(e.key==='ArrowRight')this.pos.x=Math.min(365,this.pos.x+8);if(e.key==='ArrowDown')this.pos.y=Math.min(530,this.pos.y+8);if(e.key==='ArrowUp')this.pos.y=Math.max(25-this.camera,this.pos.y-8);if(e.key===' '||e.key==='Enter')this.drop();};
 placement(){const p=createPiece(this.queue[this.count],this.pos,this.angle,difficulty[this.mode].friction);p.body.frictionAir=difficulty[this.mode].air;return p;}
 overlaps(body:Matter.Body){return Matter.Query.collides(body,Composite.allBodies(this.engine.world)).some(c=>c.depth>.5);}
 drop(){if(this.paused||this.phase!=='ready')return;const piece=this.placement();if(this.overlaps(piece.body)){this.hint='重なっています。少し上へ動かそう';this.emit();return;}Composite.add(this.engine.world,piece.body);this.pieces.push(piece);this.phase='settling';this.released=this.seconds;this.settled=0;this.stableTilt=0;this.stablePeak=0;this.hint='';this.emit();}
 end(clear:boolean){if(this.phase==='ended')return;if(clear)this.score+=clearBonus(this.seconds);this.phase='ended';this.sound.play(clear?'clear':'fail');this.finish({mode:this.mode,count:this.count,target:this.queue.length,seconds:this.seconds,clear,used:this.queue.slice(0,this.pieces.length),score:this.score,perfects:this.perfects,averageTilt:this.tiltSamples?this.tiltTotal/this.tiltSamples:0,maxTilt:this.maxTilt,failureReason:this.failureReason,order:this.queue.map(m=>m.id)});}
 supported(){
 const now=this.engine.timing.timestamp;
 for(const p of this.engine.pairs.list as Matter.Pair[])if(p.isActive)this.contacts.set(p.id,{a:p.bodyA.parent,b:p.bodyB.parent,time:now});
 for(const [key,contact] of this.contacts)if(now-contact.time>100)this.contacts.delete(key);
 const found=new Set<Matter.Body>([this.platform]);let changed=true;
 while(changed){changed=false;for(const {a,b} of this.contacts.values()){if(found.has(a)&&!found.has(b)){found.add(b);changed=true;}if(found.has(b)&&!found.has(a)){found.add(a);changed=true;}}}
 return found;
 }
 step(dt:number){if(this.paused||this.phase==='ended')return;const before=this.pieces.map(p=>({x:p.body.position.x,y:p.body.position.y,angle:p.body.angle}));this.seconds+=dt;const supported=this.supported();const load=this.pieces.reduce((mass,p,i)=>mass+(supported.has(p.body)?p.body.mass:0),0);this.bearingLoad+=(load-this.bearingLoad)*(1-Math.exp(-8*dt));applyBearing(this.platform,this.mode,this.count/this.queue.length,dt,this.bearingLoad);Engine.update(this.engine,dt*1000);limitSeesaw(this.platform);
 const degrees=Math.abs(this.platform.angle*180/Math.PI);if(this.pieces.length)this.maxTilt=Math.max(this.maxTilt,degrees);
 const fallen=this.pieces.find(p=>outside(p.body.bounds));if(fallen){const side=fallen.body.position.x<175?'左':fallen.body.position.x>215?'右':'';this.failureReason=`${fallen.member.name}が${side?`${side}へ`:""}落下。${side?'中央寄りに足場を広げよう':'支える面を広くしてみよう'}`;this.end(false);return;}
 if(this.phase==='settling'){const allStill=this.pieces.every((p,i)=>Math.hypot(p.body.position.x-before[i].x,p.body.position.y-before[i].y)/(dt*60)<difficulty[this.mode].speed&&Math.abs(p.body.angle-before[i].angle)/(dt*60)<difficulty[this.mode].spin)&&Math.abs(this.platform.angularVelocity)<.012;const support=this.supported();const connected=this.pieces.every(p=>support.has(p.body));if(allStill&&connected){this.settled+=dt;this.stableTilt+=degrees*dt;this.stablePeak=Math.max(this.stablePeak,degrees);}else{this.settled=0;this.stableTilt=0;this.stablePeak=0;}if(this.settled>=this.stableTime){const mean=this.stableTilt/this.settled;this.feedback=placementAward(mean,this.stablePeak);this.feedbackUntil=this.seconds+.95;this.score+=this.feedback.points;this.perfects+=Number(this.feedback.grade==='PERFECT');this.tiltTotal+=mean;this.tiltSamples++;this.count++;this.sound.play(this.feedback.grade==='PERFECT'?'perfect':'land');if(this.count===this.queue.length){this.end(true);return;}this.phase='ready';this.angle=0;this.pos={x:195,y:90-this.camera};this.emit();}else if(this.seconds-this.released>12){this.failureReason='揺れが収まりませんでした。低く、広い足場を作ろう';this.end(false);}}
 const top=Math.min(PIVOT.y,...this.pieces.map(p=>p.body.bounds.min.y));const desired=Math.max(0,230-top);const diff=(desired-this.camera)*.06;this.camera+=diff;if(this.phase==='ready'&&!this.drag)this.pos.y=90-this.camera;
 }
 loop=(t:number)=>{if(this.disposed)return;if(!this.last)this.last=t;const delta=Math.min((t-this.last)/1000,.05);this.last=t;this.fps=this.fps*.9+(1/(delta||1/60))*.1;if(!document.hidden&&!this.paused&&this.phase!=='ended'){this.acc+=delta;while(this.acc>=1/60&&this.phase!=='ended'){this.step(1/60);this.acc-=1/60;}}this.draw();if(t-this.ui>150){this.emit();this.ui=t;}this.raf=requestAnimationFrame(this.loop);};
 draw(){const c=this.canvas.getContext('2d')!;const dpr=Math.min(devicePixelRatio||1,2);if(this.canvas.width!==390*dpr){this.canvas.width=390*dpr;this.canvas.height=650*dpr;}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,390,650);c.save();c.translate(0,this.camera);
 c.strokeStyle='#b9dceb';c.setLineDash([2,7]);c.beginPath();c.moveTo(25,-this.camera);c.lineTo(25,650);c.moveTo(365,-this.camera);c.lineTo(365,650);c.stroke();c.setLineDash([]);
 const p=this.platform,w=this.seesaw.width;
 // Fixed support and visible central pin behind the rotating plank.
 c.fillStyle='#e6b84f';c.beginPath();c.moveTo(PIVOT.x,PIVOT.y);c.lineTo(PIVOT.x-28,616);c.quadraticCurveTo(PIVOT.x,628,PIVOT.x+28,616);c.closePath();c.fill();
 c.fillStyle='#d4a244';c.beginPath();c.roundRect(PIVOT.x-42,619,84,9,4);c.fill();
 c.save();c.translate(p.position.x,p.position.y);c.rotate(p.angle);c.fillStyle='#57b6db';c.beginPath();c.roundRect(-w/2,-8,w,16,7);c.fill();c.fillStyle='#d1f2ff';c.fillRect(-w/2+10,-7,w-20,3);
 c.strokeStyle='#ffffff80';c.lineWidth=1;for(let x=-120;x<=120;x+=30){c.beginPath();c.moveTo(x,-3);c.lineTo(x,4);c.stroke();}c.restore();
 c.fillStyle='#ffecb2';c.strokeStyle='#be9540';c.lineWidth=2;c.beginPath();c.arc(PIVOT.x,PIVOT.y,6,0,Math.PI*2);c.fill();c.stroke();


 for(const piece of this.pieces){c.save();c.translate(piece.body.position.x,piece.body.position.y);c.rotate(piece.body.angle);this.outline(c,piece.member,-piece.dx,-piece.dy);this.paint(c,piece.member,-piece.dx,-piece.dy);c.restore();if(this.debug){c.strokeStyle='#e55977';c.beginPath();piece.body.vertices.forEach((v,i)=>i?c.lineTo(v.x,v.y):c.moveTo(v.x,v.y));c.closePath();c.stroke();c.fillStyle='red';c.fillRect(piece.body.position.x-2,piece.body.position.y-2,4,4);}}
 if(this.phase==='ready'){const m=this.queue[this.count];if(this.settings.guide){c.strokeStyle='#70bcda88';c.setLineDash([4,6]);c.beginPath();c.moveTo(this.pos.x,this.pos.y+m.height/2+5);c.lineTo(this.pos.x,PIVOT.y-8+(this.pos.x-PIVOT.x)*Math.tan(this.platform.angle));c.stroke();c.setLineDash([]);}c.save();c.translate(this.pos.x,this.pos.y);c.rotate(this.angle);this.outline(c,m,-m.width/2,-m.height/2,this.overlaps(this.placement().body));c.shadowColor='#5eb5d955';c.shadowBlur=8;this.paint(c,m,-m.width/2,-m.height/2);c.restore();if(this.settings.names){c.font='600 12px sans-serif';c.textAlign='center';c.fillStyle='#43758b';c.fillText(m.name,this.pos.x,this.pos.y+m.height/2+17);}}
 c.restore();if(this.debug){c.fillStyle='#24485c';c.font='11px monospace';const b=this.pieces.at(-1)?.body;c.fillText(`FPS ${this.fps.toFixed(0)} bodies ${this.pieces.length+1} v ${b?.speed.toFixed(2)??0} ω ${b?.angularVelocity.toFixed(3)??0}`,10,630);c.fillText(`vertices ${b?.vertices.length??0} stable ${this.settled.toFixed(2)} camera ${this.camera.toFixed(0)}`,10,644);}}
 outline(c:CanvasRenderingContext2D,m:Member,x:number,y:number,blocked=false){c.save();c.translate(x,y);c.beginPath();m.collisionShape.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle=blocked?'#ec869544':'#ffffff66';c.strokeStyle=blocked?'#c55d76':'#6696aa88';c.lineWidth=1;c.fill();c.stroke();c.restore();}
 paint(c:CanvasRenderingContext2D,m:Member,x:number,y:number){const im=this.images.get(m.id);if(im?.complete&&im.naturalWidth){const scale=Math.min(m.width/im.naturalWidth,m.height/im.naturalHeight);const w=im.naturalWidth*scale,h=im.naturalHeight*scale;c.drawImage(im,x+(m.width-w)/2,y+(m.height-h)/2,w,h);}else{c.fillStyle='#8ed5ee';c.fillRect(x,y,m.width,m.height);}}
 dispose(){this.disposed=true;this.resizeObserver.disconnect();cancelAnimationFrame(this.raf);this.sound.dispose();this.canvas.removeEventListener('pointerdown',this.down);this.canvas.removeEventListener('pointermove',this.move);this.canvas.removeEventListener('pointerup',this.up);this.canvas.removeEventListener('pointercancel',this.cancel);this.canvas.removeEventListener('keydown',this.key);this.contacts.clear();Composite.clear(this.engine.world,false);Engine.clear(this.engine);}
}
