import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,inside} from '../public/shonin-defense/engine.js';
import {decision} from '../scripts/shonin-controller.mjs';
function advance(g:Game,sec:number){for(let i=0;i<sec*120;i++)g.update(1/120);}
function live(){const g=new Game(42);g.start();advance(g,1.7);g.enemies=[];g.formation=1;g.progress=-1000;return g;}
test('manual aim is independent of movement and does not track targets',()=>{const g=live();g.aim(0,-1,true);g.move(1,0);const y=g.y;advance(g,.1);assert.equal(g.angle,-Math.PI/2);assert.ok(g.bullets.some((b:{vy:number})=>b.vy<0));assert.equal(g.y,y);});
test('releasing fire charges a piercing shot; normal shots do not erase danger',()=>{const g=live();g.aim(1,0,false);advance(g,1.15);g.aim(1,0,true);advance(g,.01);assert.equal(g.chargedShots,1);assert.ok(g.bullets.some((b:{heavy:boolean})=>b.heavy));g.hazards=[{x:g.x+100,y:g.y,vx:0,vy:0,r:6,life:5}];advance(g,.2);assert.equal(g.hazards.length,1);});
test('front armor admits charged shots or a shot from behind',()=>{const g=live();const e=g.spawn('clip',400,300);g.hit(e,1,{ox:100});assert.equal(e.hp,6);g.hit(e,1,{ox:450});assert.equal(e.hp,5);g.hit(e,4,{ox:100,heavy:true});assert.equal(e.hp,1);});
test('source protection trades subordinate score for immediate safety',()=>{const g=live();const source=g.spawn('source',500,300);const paper=g.spawn('paper',430,300,{owner:source.id});g.hit(paper,9);assert.equal(paper.hp,2);g.hit(source,99);assert.ok(paper.dead);assert.equal(g.kills,1);assert.ok(g.items.some((i:{type:string})=>i.type==='energy'));});
test('blast is telegraphed and can damage both enemies and player',()=>{const g=live();g.x=200;g.y=300;const bomb=g.spawn('bomb',240,300);const paper=g.spawn('paper',270,300);g.hit(bomb,99);advance(g,.4);assert.equal(g.lives,5);assert.equal(paper.dead,undefined);advance(g,.3);assert.equal(g.lives,4);assert.ok(paper.dead);assert.ok(g.chains>0);});
test('attack, protection and express route consume the same reserve',()=>{const g=live();g.energy=75;assert.ok(g.burst());assert.equal(g.hold(),false);g.energy=60;g.branch('route');assert.ok(g.choose('upper'));assert.equal(g.energy,0);assert.equal(g.route,1);});
test('weapon choice is exclusive and survives the next stage',()=>{const g=live();g.branch('weapon');g.choose('lower');assert.equal(g.weapon,'spread');assert.equal(g.choice,null);g.enterStage(1);assert.equal(g.weapon,'spread');});
test('shelves and timed shutters occupy real collision space',()=>{const g=live();g.block(.5,300,100,'shutter');const o=g.blocks[0];assert.ok(inside({x:400,y:300},o));advance(g,2.6);assert.equal(o.active,false);advance(g,1.5);assert.equal(o.active,true);});
test('scroll advances faster with a forward position',()=>{const a=live(),b=live();a.x=60;b.x=650;advance(a,1);advance(b,1);assert.ok(b.progress>a.progress);});
test('parallel mechanisms must finish within a shared window',()=>{const g=live();g.stage=1;g.spawnBoss();const [a,b]=g.enemies;g.hit(a,99,{heavy:true});assert.ok(a.dormant);advance(g,3.3);assert.equal(a.dormant,false);g.hit(a,99,{heavy:true});g.hit(b,99,{heavy:true});assert.equal(g.boss.parts,0);});
test('holding an arriving seal returns it and opens final decision',()=>{const g=live();g.stage=2;g.spawnBoss();g.energy=100;g.hazards=[{x:g.x+45,y:g.y,vx:-10,vy:0,r:11,life:6,seal:true}];g.hold();advance(g,.1);assert.equal(g.reflections,1);advance(g,2);assert.ok(g.boss.hp<85);assert.ok(g.boss.open>0);});
test('seed and inputs are deterministic and retry clears run choices',()=>{const a=live(),b=live();advance(a,2);advance(b,2);assert.deepEqual(a.snapshot(),b.snapshot());a.weapon='pierce';a.route=1;a.start();assert.equal(a.weapon,'single');assert.equal(a.route,0);assert.equal(a.lives,5);});
test('both routes are playable through ordinary input on phone and PC',()=>{for(const width of [340,800])for(const route of ['upper','lower']){const g=new Game(1,'normal',width);g.start();for(let i=0;i<2400&&g.phase!=='ended';i++){const d=decision(g.snapshot(),'adaptive',route);g.move(d.x,d.y);g.aim(d.ax,d.ay,d.fire);if(d.burst)g.burst();if(d.guard)g.hold();advance(g,.1);g.events=[];}assert.equal(g.win,true,JSON.stringify(g.log));assert.equal(g.routeHistory[0].option,route);assert.ok(g.reflections>0);assert.equal(g.stageScores.length,3);}});
