import test from 'node:test';
import assert from 'node:assert/strict';
import {Game, H, COMBO_MEDAL} from '../public/shonin-defense/engine.js';
import {decision} from '../scripts/shonin-controller.mjs';
function advance(g:Game,sec:number){for(let i=0;i<sec*120;i++)g.update(1/120);}
function live(){const g=new Game(42);g.start();advance(g,2.1);return g;}
test('movement speed is bounded, shots automatic, retry restores the whole run',()=>{const g=live();g.setTarget(900);const old=g.x;g.update(.01);assert.equal(g.target,458);assert.ok(g.x-old<=4.91);advance(g,.3);assert.ok(g.bullets.length);g.weapon='wide';g.energy=0;g.lives=1;g.start();assert.equal(g.lives,4);assert.equal(g.weapon,'single');assert.equal(g.energy,100);assert.equal(g.stage,0);assert.equal(g.score,0);});
test('fixed world and fixed seed give repeatable formations',()=>{const a=live(),b=live();advance(a,12);advance(b,12);assert.deepEqual(a.snapshot(),b.snapshot());assert.equal(a.y,H-72);});
test('new attempts can change route but first lessons stay stable',()=>{const a=new Game(1),b=new Game(8712);a.start();b.start();advance(a,3);advance(b,3);assert.ok(a.enemies.every((e:{pattern:string})=>e.pattern==='line'));assert.ok(b.enemies.every((e:{pattern:string})=>e.pattern==='line'));});
test('three missed requests cost a life; a miss also breaks the combo',()=>{const g=live();g.combo=7;for(let i=0;i<2;i++)g.escape({x:10,form:-1});assert.equal(g.lives,4);assert.equal(g.backlog,2);assert.equal(g.combo,0);g.escape({x:10,form:-1});assert.equal(g.lives,3);assert.equal(g.backlog,0);});
test('shield and grace period absorb damage without a death cascade',()=>{const g=live();g.shield=1;g.damage();assert.equal(g.shield,0);assert.equal(g.lives,4);g.damage();assert.equal(g.lives,4);g.invincible=0;g.damage();g.damage();assert.equal(g.lives,3);assert.equal(g.hits,1);});
test('a returned request relocates once, then can be approved',()=>{const g=live();const e={id:999,type:'return',x:100,base:100,y:300,hp:2,speed:40,returned:false,form:-1};g.hitEnemy(e);assert.equal(e.returned,true);assert.equal(e.x,380);assert.equal(g.kills,0);g.hitEnemy(e);g.hitEnemy(e);assert.equal(g.kills,1);g.hitEnemy(e);assert.equal(g.kills,1);});
test('burst has a real opportunity cost and cannot immediately pay for itself',()=>{const g=live();g.enemies=[{id:999,type:'normal',x:100,y:100,hp:2,form:-1}];g.hazards=[{x:10,y:10}];assert.ok(g.burst());assert.equal(g.energy,0);assert.equal(g.combo,0);assert.equal(g.score,85);assert.equal(g.burst(),false);assert.equal(g.hazards.length,0);});
test('full formations give a bonus; denial forfeits the full-approval bonus',()=>{const a=live();a.enemies=[];a.formationWave();for(const e of a.enemies)a.kill(e);assert.equal(a.perfects,1);const b=live();b.enemies=[];b.formationWave();for(const e of b.enemies)b.kill(e,true);assert.equal(b.perfects,0);assert.ok(a.score>b.score);});
test('telegraphed aimed attacks lock the old player position',()=>{const g=live();g.warning('aim',120,20,1,{y:150,speed:180});g.update(.01);g.setTarget(430);advance(g,.98);assert.equal(g.hazards.length,0);advance(g,.04);assert.ok(g.hazards.length>0);assert.ok(g.hazards[0].vx<60);});
test('beam has no hitbox during warning and respects its firing duration',()=>{const g=live();g.warning('beam',240,82,1.2,{duration:.6});advance(g,1);assert.equal(g.lives,4);advance(g,.3);assert.equal(g.lives,3);g.setTarget(430);advance(g,.6);assert.equal(g.hazards.filter((b:{kind:string})=>b.kind==='beam').length,0);});
test('graze only charges once per projectile',()=>{const g=live();g.energy=0;g.addHazard(g.x+22,g.y,0,0,'dot',6);advance(g,.1);assert.equal(g.grazes,1);assert.equal(g.energy,3);advance(g,.1);assert.equal(g.energy,3);});
test('boss one requires both nodes before the central core opens',()=>{const g=live();g.spawnBoss();const b=g.boss;assert.equal(g.hitBoss(b.x,99),false);for(const n of b.nodes)g.hitBoss(b.x+n.side*72,10);g.bossUpdate(.01);assert.equal(b.open,true);g.hitBoss(b.x,99);assert.equal(g.segment,'clear');assert.equal(g.phase,'playing');advance(g,2.5);assert.equal(g.phase,'upgrade');});
test('equipment selection is validated, repairs one life and advances the stage',()=>{const g=live();g.lives=2;g.spawnBoss();g.defeatBoss();advance(g,2.5);assert.equal(g.lives,3);assert.equal(g.chooseUpgrade('unknown'),false);assert.equal(g.chooseUpgrade('pierce'),true);assert.equal(g.weapon,'pierce');assert.equal(g.stage,1);assert.equal(g.chooseUpgrade('wide'),false);});
test('boss two rejects hits while closed and off its weak point',()=>{const g=live();g.stage=1;g.spawnBoss();g.bossUpdate(.1);const b=g.boss;assert.equal(b.open,false);assert.equal(g.hitBoss(b.weakX,10),false);b.age=3;g.bossUpdate(.01);assert.equal(b.open,true);assert.equal(g.hitBoss(b.weakX+70),false);assert.ok(g.hitBoss(b.weakX));});
test('boss attacks always have readable warnings and a visible deadline',()=>{const g=live();g.stage=2;g.spawnBoss();g.boss.attack=0;g.bossUpdate(.01);assert.ok(g.warnings[0].left>=.9);assert.equal(g.hazards.length,0);g.bossTime=55;g.bossUpdate(.01);assert.equal(g.phase,'ended');assert.match(g.reason,/締切/);});
test('the third boss ends the run after a clear beat, not an upgrade menu',()=>{const g=live();g.stage=2;g.spawnBoss();g.defeatBoss();advance(g,2.5);assert.equal(g.phase,'ended');assert.equal(g.win,true);assert.ok(g.score>0);});
test('coffee and energy items work without lasting power loss on damage',()=>{const g=live();g.energy=10;g.items=[{x:g.x,y:g.y,type:'energy'},{x:g.x,y:g.y,type:'coffee'}];g.update(.01);assert.equal(g.energy,45);assert.equal(g.coffee,7);g.weapon='pierce';g.damage();assert.equal(g.weapon,'pierce');});

test('a full normal run and its combo medal are reachable through public inputs',()=>{const g=new Game(1);g.start();let tick=0;while(g.phase!=='ended'&&tick<24000){if(g.phase==='upgrade')g.chooseUpgrade(g.stage===0?'pierce':'shield');if(tick%12===0){const d=decision(g.snapshot());g.setTarget(d.x);if(d.burst)g.burst();}g.update(1/120);g.events=[];tick++;}assert.equal(g.win,true);assert.ok(g.maxCombo>=COMBO_MEDAL);assert.ok(g.perfects>=8);assert.equal(g.stageScores.length,3);});
