import test from 'node:test';
import assert from 'node:assert/strict';
import {Game, H, blocksLine} from '../public/shonin-defense/engine.js';
import {decision} from '../scripts/shonin-controller.mjs';
function advance(g:Game,sec:number){for(let i=0;i<sec*120;i++)g.update(1/120);}
function live(){const g=new Game(42);g.start();advance(g,1.7);g.enemies=[];g.formation=0;g.waveAge=-100;return g;}
test('all-direction movement is bounded, diagonal normalized, release decelerates',()=>{const a=live(),b=live();a.move(1,1);b.move(1,0);const ax=a.x,ay=a.y,bx=b.x;advance(a,.3);advance(b,.3);assert.ok(a.y>ay);assert.ok(Math.abs(Math.hypot(a.x-ax,a.y-ay)-(b.x-bx))<.01);a.move(0,0);advance(a,.3);assert.ok(Math.abs(a.vx)<1);assert.equal(H,600);});
test('seed, movement and timestep produce deterministic replay; reset removes progression',()=>{const a=live(),b=live();advance(a,4);advance(b,4);assert.deepEqual(a.snapshot(),b.snapshot());a.weapon='wide';a.lives=1;a.score=900;a.start();assert.equal(a.weapon,'single');assert.equal(a.lives,4);assert.equal(a.score,0);});
test('spawn protection makes an announced enemy harmless until arrival',()=>{const g=live();g.spawn('chaser',g.x,g.y);advance(g,.8);assert.equal(g.lives,4);assert.equal(g.kills,0);advance(g,.4);assert.equal(g.lives,3);});
test('aim attacks lock coordinates and warning itself does no damage',()=>{const g=live();g.warn('shot',{x:240,y:100},g,1);g.move(1,0);advance(g,.8);assert.equal(g.hazards.length,0);advance(g,.3);assert.ok(g.hazards.length);assert.ok(Math.abs(g.hazards[0].vx)<.01);});
test('attack director limits simultaneous warnings and cancels dead rush sources',()=>{const g=live();for(let i=0;i<8;i++)g.warn('shot',{x:50,y:80},g,1);assert.equal(g.warnings.length,3);g.warnings=[];g.spawn('urgent',150,150);const e=g.enemies[0];g.warn('rush',e,g,1,{owner:e.id});g.hit(e,99);advance(g,1.1);assert.equal(g.hazards.length,0);});
test('fixtures block movement, line of sight, and bullets',()=>{const g=live();g.blocks=[{x:240,y:300,r:30}];g.x=240;g.y=350;g.move(0,-1);advance(g,.5);assert.ok(g.y>=340);assert.equal(blocksLine({x:240,y:400},{x:240,y:200},g.blocks),true);g.projectile(240,340,-Math.PI/2,100);advance(g,.3);assert.equal(g.hazards.length,0);});
test('local counter dash clears nearby bullets but leaves remote danger and beams',()=>{const g=live();g.projectile(g.x+30,g.y,0,0);g.projectile(40,100,0,0);g.hazards.push({kind:'beam',x:30,y:80,tx:30,ty:500,r:12,life:.6});g.move(1,0);assert.ok(g.burst());assert.equal(g.burst(),false);assert.equal(g.reflected,1);assert.equal(g.hazards.filter((h:{life:number})=>h.life>0).length,2);const x=g.x;advance(g,.15);assert.ok(g.x-x>70);assert.ok(g.invincible>0);});
test('damage grace and proxy shield prevent repeated contact death; no permanent power loss',()=>{const g=live();g.shield=1;g.weapon='pierce';g.damage('test');g.damage('test');assert.equal(g.lives,4);g.invincible=0;g.damage('test');g.damage('test');assert.equal(g.lives,3);assert.equal(g.weapon,'pierce');});
test('close approvals reward position and stamps reward collection',()=>{const near=live(),far=live();near.spawn('chaser',near.x+40,near.y);far.spawn('chaser',80,80);near.hit(near.enemies[0],10);far.hit(far.enemies[0],10);assert.ok(near.score>far.score);near.items=[{x:near.x,y:near.y,type:'stamp',life:5}];near.energy=0;advance(near,.01);assert.equal(near.stamps,1);assert.ok(near.energy>=10);});
test('return request respawns with a warning, and cannot split forever',()=>{const g=live();g.spawn('return',150,180);g.hit(g.enemies[0],10);const e=g.enemies.find((e:{returned:boolean})=>e.returned);assert.ok(e.spawn>=1.3);g.hit(e,10);assert.equal(g.kills,2);assert.equal(g.enemies.filter((e:{dead:boolean})=>!e.dead).length,0);});
test('first boss exposes core only after its committed rush',()=>{const g=live();g.spawnBoss();g.bossUpdate(.1);assert.equal(g.boss.open,false);g.boss.state='rush';g.boss.timer=.01;g.boss.speed=350;g.boss.angle=0;g.bossUpdate(.02);g.bossUpdate(.01);assert.equal(g.boss.open,true);});
test('routing boss requires both relay nodes, then exposes core',()=>{const g=live();g.stage=1;g.spawnBoss();g.bossUpdate(.1);assert.equal(g.boss.open,false);for(const e of g.enemies)g.hit(e,99);g.bossUpdate(.1);assert.equal(g.boss.open,true);});
test('deadline beam warns then activates and expires; last boss ends run',()=>{const g=live();g.warn('beam',{x:g.x,y:60},{x:g.x,y:560},1,{width:20});advance(g,.9);assert.equal(g.lives,4);advance(g,.2);assert.equal(g.lives,3);advance(g,.7);assert.equal(g.hazards.length,0);g.stage=2;g.spawnBoss();g.defeatBoss();advance(g,2);assert.equal(g.win,true);assert.equal(g.phase,'ended');});
test('validated intermission choice heals once and advances to changed space',()=>{const g=live();g.lives=2;g.spawnBoss();g.defeatBoss();advance(g,2);assert.equal(g.phase,'upgrade');assert.equal(g.lives,3);assert.equal(g.chooseUpgrade('invalid'),false);assert.equal(g.chooseUpgrade('pierce'),true);assert.equal(g.stage,1);assert.equal(g.blocks.length,2);assert.equal(g.chooseUpgrade('wide'),false);});
test('full route is reachable by ordinary movement and action, without hidden cheats',()=>{const g=new Game(1);g.start();let frames=0;while(g.phase!=='ended'&&frames++<3000){if(g.phase==='upgrade')g.chooseUpgrade(g.stage===0?'pierce':'shield');const d=decision(g.snapshot());g.move(d.x,d.y);if(d.burst)g.burst();advance(g,.1);g.events=[];}assert.equal(g.win,true);assert.equal(g.stageScores.length,3);assert.ok(g.stamps>=27);});

test('month-end seals stop damage at each threshold and telegraph a new direction',()=>{const g=live();g.stage=2;g.spawnBoss();const b=g.boss;b.open=true;g.hit(b,50);assert.equal(b.hp,40);assert.equal(b.seal,1);assert.equal(b.open,false);assert.equal(g.warnings[0].kind,'beam');g.hit(b,99);assert.equal(b.hp,40);b.open=true;g.hit(b,30);assert.equal(b.hp,20);assert.equal(b.seal,2);b.open=true;g.hit(b,20);assert.equal(g.segment,'clear');});
