import fs from 'node:fs/promises';import {existsSync} from 'node:fs';import {createHash} from 'node:crypto';import * as cheerio from 'cheerio';import sharp from 'sharp';import {members} from '../src/data/members';
await fs.mkdir('.cache/blog-photos',{recursive:true});await fs.mkdir('.cache/blog-sheets',{recursive:true});
async function get(url:string){const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`${r.status}: ${url}`);return Buffer.from(await r.arrayBuffer());}
const only=process.argv.slice(2);const reports=[];
for(const m of members.filter(m=>!only.length||only.includes(m.id))){
 const page=`https://www.hinatazaka46.com/s/official/diary/member/list?ct=${m.id}&ima=0000`;
 const cache=`.cache/blog-photos/${m.id}-list.html`;if(!existsSync(cache))await fs.writeFile(cache,await get(page));const $=cheerio.load(await fs.readFile(cache,'utf8'));const candidates:any[]=[];const seen=new Set();
 $('.p-blog-article').each((_,el)=>{const a=$(el);const author=a.find('.c-blog-article__name').text().trim();if(author.replace(/\s/g,'')!==m.name.replace(/\s/g,''))return;const article=new URL(a.find('.c-button-blog-detail').attr('href')||page,page).href;const title=a.find('.c-blog-article__title').text().trim();a.find('.c-blog-article__text img').each((_,img)=>{const src=$(img).attr('src');if(!src)return;const url=new URL(src,page).href;if(!url.includes('/diary/')||seen.has(url))return;seen.add(url);candidates.push({url,page:article,title,author});});});
 const photos=[];for(let start=0;start<Math.min(candidates.length,Number(process.env.PHOTO_LIMIT||64));start+=4){const batch=await Promise.allSettled(candidates.slice(start,start+4).map(async(c:any,index:number)=>{const key=createHash('sha256').update(c.url).digest('hex').slice(0,12),raw=`.cache/blog-photos/${m.id}-${key}.jpg`;if(!existsSync(raw))await fs.writeFile(raw,await get(c.url));const meta=await sharp(raw).metadata();return{...c,index:start+index,raw,width:meta.width,height:meta.height};}));for(const r of batch)if(r.status==='fulfilled')photos.push(r.value);else console.error(m.name,String(r.reason));}
 await fs.writeFile(`.cache/blog-photos/${m.id}.json`,JSON.stringify({id:m.id,name:m.name,photos},null,2));
 const portraits=photos.filter(p=>p.width!>=300&&p.height!>=p.width!*.95);const layers=[];for(let i=0;i<portraits.length;i++){const p=portraits[i],x=i%8*150,y=Math.floor(i/8)*210;layers.push({input:await sharp(p.raw).resize(146,182,{fit:'contain',background:'#eeeeee'}).png().toBuffer(),left:x,top:y});layers.push({input:Buffer.from(`<svg width="150" height="26"><text x="5" y="20" font-size="17">${m.id} : ${p.index}</text></svg>`),left:x,top:y+184});}
 if(layers.length)await sharp({create:{width:1200,height:Math.ceil(portraits.length/8)*210,channels:3,background:'white'}}).composite(layers).jpeg({quality:85}).toFile(`.cache/blog-sheets/${m.id}.jpg`);
 console.log(`${m.name}: ${photos.length} photos, ${portraits.length} portraits`);reports.push({id:m.id,total:photos.length});
}
