import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.GAME_URL||'http://127.0.0.1:4173/hinata-balance/';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});await page.goto(base+'?debug=true');await page.locator('h1').waitFor();
 const manifest=await (await page.request.get(base+'manifest.webmanifest')).json();assert.equal(manifest.scope,new URL(base).pathname);assert.equal(manifest.start_url,new URL(base).pathname);assert.equal(manifest.display,'standalone');
 await page.waitForFunction(async()=>!!(await navigator.serviceWorker.ready).active);await page.reload();
 const assets=await fs.readdir('public/assets/members');for(const file of assets){const response=await page.request.get(base+'assets/members/'+file);assert.equal(response.status(),200,file);assert.match(response.headers()['content-type'],/image\/webp/);}
 const cdp=await context.newCDPSession(page);
 for(const mode of ['NORMAL','HARD','ALL MEMBERS']){await page.goto(base+'?debug=true');await page.getByRole('button',{name:new RegExp(mode)}).click();await page.getByRole('button',{name:'右へ回転'}).tap();assert.equal(Math.round(await page.evaluate(()=>window.__hinataGame.angle*180/Math.PI)),15);await page.getByRole('button',{name:'左へ回転'}).tap();const b=await page.locator('canvas').boundingBox();const x=b.x+b.width/2;const y=b.y+90/650*b.height;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=10;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+400/650*b.height*i/10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForFunction(()=>window.__hinataGame.count===1,null,{timeout:15000});assert.equal(await page.evaluate(()=>scrollY),0);}
 await page.evaluate(()=>localStorage.setItem('hinata-settings',JSON.stringify({bgm:false,se:false,vibration:false,names:true,guide:true})));await page.goto(base);await page.getByRole('button',{name:/SETTINGS/}).click();await page.getByText('v'+JSON.parse(await fs.readFile('package.json','utf8')).version,{exact:true}).waitFor();await page.reload();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('hinata-settings')).se),false);
 await context.setOffline(true);await page.goto(base);await page.locator('h1').waitFor();await page.getByRole('button',{name:/NORMAL/}).click();await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await page.screenshot({path:'.cache/pages-mobile.png'});assert.deepEqual(errors,[]);console.log(JSON.stringify({base,manifest,images:assets.length,touchAllModes:true,rotation:true,storage:true,offline:true,errors},null,2));await fs.writeFile(new URL(base).protocol==='https:'?'docs/pages-public-check.json':'docs/pages-local-check.json',JSON.stringify({base,images:assets.length,touchAllModes:true,rotation:true,storage:true,offline:true,errors},null,2));
}finally{await browser.close();}
